/**
 * @description       : 
 * @author            : Vaibhav Srivastava
 * @group             : 
 * @last modified on  : 10-07-2020
 * @last modified by  : Vaibhav Srivastava
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   10-07-2020   Vaibhav Srivastava   Initial Version
**/
public with sharing class UpdateRecordLightning {
    public CreateRecordLightning() {
 
    }
}